Traceback (most recent call last):
  File "/mnt/c/users/matt/school/2620/pset4/fault_tolerant_implementation/raft_server.py", line 519, in <module>
    serve(args.node_id, cluster_config, args.data_dir, args.port)
  File "/mnt/c/users/matt/school/2620/pset4/fault_tolerant_implementation/raft_server.py", line 474, in serve
    raft_node = RaftNode(node_id, cluster_config, data_dir)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/c/users/matt/school/2620/pset4/fault_tolerant_implementation/raft_node.py", line 80, in __init__
    self._init_database()
  File "/mnt/c/users/matt/school/2620/pset4/fault_tolerant_implementation/raft_node.py", line 127, in _init_database
    c.execute('''
sqlite3.OperationalError: unrecognized token: "#"
